paths:
  raw_inputs: "01-inputs" # Datos crudos de audio/video
  audio: "01-inputs/audio" # Salida de utilitarios.preparaaudios
  transcriptions: "02-transcripciones" # Salida de ingest.transcribe
  metadata: "03-metadata" # Salida de process.resumen y, a futuro, otros.
  templates: "04-templates" # Plantillas para deliver.llenado
  outputs: "05-outputs" # Documentos finales

models:
  whisper: "base" # Modelo Whisper para transcripción
  gemini: "gemini-2.0-flash-001" # Modelo Google Gemini para engine=gemini

prompts:
  resumen: Eres un asistente experto en resumir entrevistas técnicas.
    Genera un resumen temático e índice de tópicos en español.
  llenado: llena la planilla # este hay que traerlo todavía

process:
  engine: "gemini"

deliver:
  engine: "gemini"

templates:
  default: "default.md"
  jubilados: "jubilados.md"
  capacita: "capacita.md"

estrategia:
  default: "estrategia.md"
